### ISSUE TITLE
minor errors running installation as described in README

### ISSUE THREAD

**Issue by rodriguez-facundo** [MetaCell/scidash#48]
I encountered the following issues following the installation steps (on macOS):
-  `pip install -r requirements.txt` failed because **psycopg2** package requires **libpq-dev**.  Running `brew install postgresql ` **before** running `pip install -r requirements.txt`  solved it.
- `npm run build-dev-noTest` should be executed **after** cloning **geppetto-scidash**  extension and modification of GeppettoConfiguration.json.
- `mkdir static` was not required.
- python<=3.6.5 was required

**Comment by gidili** [comment]
@rodriguez-facundo wanna update the readme and open a PR? 😃

**Comment by rodriguez-facundo** [comment]
yes sure

**Comment by rodriguez-facundo** [comment]
https://github.com/MetaCell/scidash/commit/99214289c8d79fff43cff45488022c691f0487dd
